### ISSUE TITLE
Suspended account kpei.me

### ISSUE THREAD

**Issue by zbazanowski** [kpei/Customer-Analytics#1]
Hi Kevin,
your blog on kpei.me has been suspended.

I would like to read your excellen contribution http://kpei.me/blog/?p=921:
Lifetimes Part 1: Customer Analytics | Kevin Pei
Especially I am interested in your mathematical part.

I wonder if you could publish that page somewhere else?

I would appreciate is if you could.

My email: zbynekb@gmail.com

**Comment by kpei** [comment]
online
